import { FOO_PATTERN } from './examplePatterns';

const INITIAL_LIVE_CELLS = FOO_PATTERN;
const INITIAL_BOARD_WIDTH = 40;
const INITIAL_BOARD_HEIGHT = 30;
const INITIAL_MIN_BOARD_WIDTH = 10;
const INITIAL_MIN_BOARD_HEIGHT = 10;
const INITIAL_MAX_BOARD_WIDTH = 120;
const INITIAL_MAX_BOARD_HEIGHT = 80;
const INITIAL_TICK_DELAY = 200;

export default {
  INITIAL_LIVE_CELLS,
  INITIAL_BOARD_WIDTH,
  INITIAL_BOARD_HEIGHT,
  INITIAL_MIN_BOARD_WIDTH,
  INITIAL_MIN_BOARD_HEIGHT,
  INITIAL_MAX_BOARD_WIDTH,
  INITIAL_MAX_BOARD_HEIGHT,
  INITIAL_TICK_DELAY
};
